[package]
name = "gitviz"
version = "0.2.0"
description = "gitviz - game-save metaphor git GUI desktop"
authors = ["Harly <1211074765@qq.com>"]
license = "MIT"
repository = "https://github.com/fisHarly0/gitviz"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.2", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.2", features = [] }
tauri-plugin-log = "2"
gix = { version = "0.73.0", features = ["tree-editor"] }
tokio = { version = "1.52.3", features = ["full"] }
tauri-plugin-dialog = "2.7.1"
chrono = "0.4.44"
serde_bytes = "0.11.19"
