const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const path = require('node:path')
const os = require('node:os')
const { GitService } = require('../extensions/vscode/git-service.cjs')
const testRoot = process.env.GITVIZ_TEST_ROOT || (process.platform === 'win32' ? 'F:/Codex/work/gitviz-tests' : path.join(os.tmpdir(), 'gitviz-tests'))

test('prepared confirmations identify repository, full targets, file impact and unchanged original directory', async () => {
  const f = await fixture()
  for (let i = 0; i < 12; i++) await f.put(`中文 ${i}.txt`, 'first\n')
  const first = await f.commit('first')
  for (let i = 0; i < 12; i++) await f.put(`中文 ${i}.txt`, 'second\n')
  const expected = await f.expected(), second = await f.commit('second')
  expected.head = second
  const directory = path.join(testRoot, 'preview-only-directory')
  for (const action of ['createBranch', 'createWorktree', 'restore']) {
    const plan = await f.repo.prepareAction(action, { oid: first, name: 'preview-branch', directory, expected })
    assert.equal(plan.preview.expected.repo, f.root)
    assert.equal(plan.preview.expected.head, second)
    assert.equal(plan.preview.target, first)
    assert.equal(plan.preview.files.length, 12)
    const text = GitService.confirmationText(plan.preview)
    assert.ok(text.includes(f.root) && text.includes(first) && text.includes(second))
    assert.match(text, /其余 4 个文件未展开/)
    if (action !== 'restore') assert.match(plan.preview.filesLabel, /原目录不变/)
    if (action === 'createWorktree') assert.equal(plan.preview.directory, path.resolve(directory))
  }
  assert.equal(await f.repo.head(), second)
  assert.equal(await f.repo.status(), '')
  assert.equal((await f.repo.operations()).records.length, 0)
  assert.equal((await f.repo.snapshot()).branches.length, 1)
})

test('prepared switch rejects an externally moved target even when current HEAD is unchanged', async () => {
  const f = await fixture()
  await f.put('a.txt', 'first'); const first = await f.commit('first')
  await f.put('a.txt', 'second'); const second = await f.commit('second')
  await f.repo.command(['branch', 'other', first])
  const plan = await f.repo.prepareAction('switchBranch', { name: 'other', expected: await f.expected() })
  assert.equal(plan.preview.target, first)
  assert.deepEqual(plan.preview.files, ['a.txt'])
  await f.repo.command(['update-ref', 'refs/heads/other', second, first])
  await assert.rejects(f.repo.executePrepared(plan), /历史已变化/)
  await assert.rejects(f.repo.executePrepared(plan), /已使用/)
  assert.equal(await f.repo.branch(), 'main')
  assert.equal(await f.repo.head(), second)
  assert.equal(await f.repo.status(), '')
  assert.equal((await f.repo.operations()).records.length, 0)
  const fresh = await f.repo.prepareAction('switchBranch', { name: 'other', expected: await f.expected() })
  await f.repo.executePrepared(fresh)
  assert.equal(await f.repo.branch(), 'other')
})

test('prepared actions expire and are bound to their repository, with no journal entry on rejection', async () => {
  const f = await fixture(), other = await fixture()
  await f.put('a.txt', 'first'); const first = await f.commit('first')
  await other.put('b.txt', 'other'); await other.commit('other')
  const params = { oid: first, name: 'expired', expected: await f.expected() }
  const expired = await f.repo.prepareAction('createBranch', params)
  expired.expires = Date.now() - 1
  await assert.rejects(f.repo.executePrepared(expired), /过期/)
  const wrong = await f.repo.prepareAction('createBranch', params)
  await assert.rejects(other.repo.executePrepared(wrong), /仓库已变化|不是|提交|bad object/)
  assert.equal((await f.repo.snapshot()).branches.length, 1)
  assert.equal((await f.repo.operations()).records.length, 0)
  assert.equal((await other.repo.operations()).records.length, 0)
})

test('preview rejects a target update while the initial history snapshot is being read', async () => {
  const f = await fixture()
  await f.put('a.txt', 'first'); const first = await f.commit('first')
  await f.put('a.txt', 'second'); const second = await f.commit('second')
  await f.repo.command(['branch', 'target', first])
  const readHistory = f.repo.historyState.bind(f.repo)
  let changed = false
  f.repo.historyState = async () => {
    const state = await readHistory()
    if (!changed) {
      changed = true
      await f.repo.command(['update-ref', 'refs/heads/target', second, first])
    }
    return state
  }
  await assert.rejects(f.repo.prepareAction('switchBranch', { name: 'target', expected: await f.expected() }), /历史已变化/)
  assert.equal(await f.repo.branch(), 'main'); assert.equal(await f.repo.head(), second)
  assert.equal(await f.repo.status(), '')
  assert.equal((await f.repo.operations()).records.length, 0)
})

async function fixture() {
  await fs.mkdir(testRoot, { recursive: true })
  const root = await fs.mkdtemp(path.join(testRoot, 'repo-'))
  const repo = new GitService(root)
  await repo.command(['init', '-b', 'main'])
  await repo.command(['config', 'user.name', 'Gitviz Test Fixture'])
  await repo.command(['config', 'user.email', 'fixture@example.invalid'])
  await repo.command(['config', 'commit.gpgsign', 'false'])
  await repo.command(['config', 'core.autocrlf', 'false'])
  const put = async (name, content) => { await fs.mkdir(path.dirname(path.join(root, name)), { recursive: true }); await fs.writeFile(path.join(root, name), content) }
  const commit = async message => { await repo.command(['add', '--all']); await repo.command(['commit', '-m', message]); return repo.head() }
  const expected = async () => ({ head: await repo.head(), branch: await repo.branch() })
  return { root, repo, put, commit, expected }
}

test('empty repository, root commit, unicode and special filenames', async () => {
  const f = await fixture()
  assert.deepEqual((await f.repo.snapshot()).commits, [])
  const name = '中文 space $name [1].txt'
  await f.put(name, '最初内容\n')
  const first = await f.commit('起点 · 中文')
  const data = await f.repo.snapshot()
  assert.equal(data.commits[0].message, '起点 · 中文')
  assert.equal(data.branch, 'main'); assert.equal(data.head, first)
  const detail = await f.repo.detail(first)
  assert.equal(detail.from, null); assert.equal(detail.files[0].status, 'A')
  assert.equal(await f.repo.readFile(first, name), '最初内容\n')
  assert.equal(await f.repo.readFile(first, 'absent.txt'), '')
  assert.equal(await f.repo.readFile(null, name), '')
})

test('real merge includes both parents, annotated tag, detached HEAD', async () => {
  const f = await fixture()
  await f.put('base.txt', 'base'); const root = await f.commit('base')
  await f.repo.command(['switch', '-c', 'feature'])
  await f.put('feature.txt', 'feature'); const feature = await f.commit('feature')
  await f.repo.command(['switch', 'main'])
  await f.put('main.txt', 'main'); const main = await f.commit('main')
  await f.repo.command(['merge', '--no-ff', 'feature', '-m', 'merge'])
  const head = await f.repo.head()
  await f.repo.command(['tag', '-a', 'v1', '-m', 'release'])
  const data = await f.repo.snapshot()
  assert.deepEqual(data.commits[0].parents, [main, feature])
  assert.equal(data.tags[0].oid, head); assert.equal(data.commits.length, 4)
  await f.repo.command(['switch', '--detach', root])
  assert.equal((await f.repo.snapshot()).branch, '')
  await assert.rejects(() => f.repo.restore(feature, { head: root, branch: '' }), /游离/)
})

test('rename and deleted/added contents are directional', async () => {
  const f = await fixture()
  await f.put('old name.txt', 'same\n'); await f.put('removed.txt', 'bye'); const before = await f.commit('before')
  await fs.rename(path.join(f.root, 'old name.txt'), path.join(f.root, 'new name.txt'))
  await fs.unlink(path.join(f.root, 'removed.txt')); await f.put('added.txt', 'new')
  const after = await f.commit('after')
  const files = await f.repo.files(before, after)
  assert.equal(files.find(file => file.path === 'new name.txt').oldPath, 'old name.txt')
  assert.equal(files.find(file => file.path === 'removed.txt').status, 'D')
  assert.equal(files.find(file => file.path === 'added.txt').status, 'A')
  assert.equal(await f.repo.readFile(before, 'old name.txt'), 'same\n')
  assert.equal(await f.repo.readFile(after, 'new name.txt'), 'same\n')
})

test('branch creation is non-switching and checkout synchronizes real worktree', async () => {
  const f = await fixture()
  await f.put('file.txt', 'old'); const old = await f.commit('old')
  await f.put('file.txt', 'new'); const current = await f.commit('new')
  await f.repo.createBranch(old, 'if-old', await f.expected())
  assert.equal(await f.repo.head(), current)
  await f.repo.switchBranch('if-old', await f.expected())
  assert.equal(await fs.readFile(path.join(f.root, 'file.txt'), 'utf8'), 'old')
  assert.equal(await f.repo.branch(), 'if-old')
})

test('isolated worktree leaves original dirty files and HEAD untouched', async () => {
  const f = await fixture()
  await f.put('file.txt', 'saved'); const head = await f.commit('saved')
  await f.put('file.txt', 'unsaved')
  const result = await f.repo.createWorktree(head, 'if-test', path.join(testRoot, 'worktrees'), await f.expected())
  assert.equal(await fs.readFile(path.join(result.worktree, 'file.txt'), 'utf8'), 'saved')
  assert.equal(await fs.readFile(path.join(f.root, 'file.txt'), 'utf8'), 'unsaved')
  assert.equal(await f.repo.head(), head)
  assert.equal(await f.repo.branch(), 'main')
})

test('restore creates new commit with target tree, retains history and backup', async () => {
  const f = await fixture()
  await f.put('file.txt', 'old'); await f.put('removed.txt', 'restore me'); const old = await f.commit('old')
  await f.put('file.txt', 'new'); await fs.unlink(path.join(f.root, 'removed.txt')); await f.put('added.txt', 'remove me'); const before = await f.commit('new')
  const result = await f.repo.restore(old, await f.expected())
  assert.notEqual(result.head, old); assert.notEqual(result.head, before)
  assert.equal((await f.repo.command(['rev-parse', `${result.head}^`])).trim(), before)
  assert.equal((await f.repo.command(['rev-parse', `${old}^{tree}`])).trim(), (await f.repo.command(['rev-parse', 'HEAD^{tree}'])).trim())
  assert.equal((await f.repo.command(['rev-parse', result.backup])).trim(), before)
  assert.equal(await f.repo.status(), '')
  assert.equal(await fs.readFile(path.join(f.root, 'file.txt'), 'utf8'), 'old')
  assert.equal(await fs.readFile(path.join(f.root, 'removed.txt'), 'utf8'), 'restore me')
  assert.equal(await fs.stat(path.join(f.root, 'added.txt')).catch(() => null), null)
  await f.repo.command(['fsck', '--no-dangling'])
})

test('dirty/untracked files, stale HEAD and busy operations reject mutations', async () => {
  const f = await fixture()
  await f.put('file.txt', 'old'); const old = await f.commit('old'); const expected = await f.expected()
  await f.put('new.txt', 'untracked')
  await assert.rejects(() => f.repo.restore(old, expected), /未提交/)
  await assert.rejects(() => f.repo.switchBranch('main', expected), /未提交/)
  await f.commit('new')
  await assert.rejects(() => f.repo.restore(old, expected), /已变化/)
  f.repo.busy = true
  await assert.rejects(() => f.repo.createBranch(old, 'nope', expected), /正在进行/)
})

test('ignored files that would be overwritten are protected', async () => {
  const f = await fixture()
  await f.put('cache.txt', 'tracked old'); const old = await f.commit('old')
  await fs.unlink(path.join(f.root, 'cache.txt')); await f.put('.gitignore', 'cache.txt\n'); const current = await f.commit('ignore')
  await f.put('cache.txt', 'precious ignored')
  await assert.rejects(f.repo.prepareAction('restore', { oid: old, expected: { head: current, branch: 'main' } }), /被忽略/)
  await assert.rejects(() => f.repo.restore(old, { head: current, branch: 'main' }), /被忽略/)
  assert.equal(await fs.readFile(path.join(f.root, 'cache.txt'), 'utf8'), 'precious ignored')
  assert.equal(await f.repo.head(), current)
  assert.equal((await f.repo.operations()).records.length, 0)
})

test('restore preview rejects invalid identity before creating a backup or operation record', async () => {
  const f = await fixture()
  await f.put('a.txt', 'first'); const first = await f.commit('first')
  await f.put('a.txt', 'second'); const head = await f.commit('second')
  await f.repo.command(['config', 'user.name', ''])
  const expected = await f.expected(), index = await fs.readFile(path.join(f.root, '.git/index'))
  await assert.rejects(f.repo.prepareAction('restore', { oid: first, expected }), /empty ident name|identity/i)
  assert.equal(await f.repo.head(), head)
  assert.equal(await fs.readFile(path.join(f.root, 'a.txt'), 'utf8'), 'second')
  assert.deepEqual(await fs.readFile(path.join(f.root, '.git/index')), index)
  assert.equal((await f.repo.operations()).records.length, 0)
  assert.equal((await f.repo.snapshot()).branches.length, 1)
})

test('commit hook failure retains backup, target staged content and old HEAD', async () => {
  const f = await fixture()
  await f.put('file.txt', 'old'); const old = await f.commit('old')
  await f.put('file.txt', 'new'); const current = await f.commit('new')
  const hooks = path.join(f.root, '.git', 'hooks-test')
  await fs.mkdir(hooks)
  await fs.writeFile(path.join(hooks, 'pre-commit'), '#!/bin/sh\necho test-hook-rejected >&2\nexit 1\n', { mode: 0o755 })
  await f.repo.command(['config', 'core.hooksPath', hooks])
  await assert.rejects(() => f.repo.restore(old, { head: current, branch: 'main' }), /恢复未完成.*test-hook-rejected/s)
  assert.equal(await f.repo.head(), current)
  assert.equal(await fs.readFile(path.join(f.root, 'file.txt'), 'utf8'), 'old')
  assert.ok(await f.repo.status())
  assert.ok((await f.repo.snapshot()).branches.some(ref => ref.name.startsWith('gitviz/backup-') && ref.oid === current))
})

test('invalid OIDs and branch expressions never become shell commands', async () => {
  const f = await fixture()
  await f.put('file.txt', 'test'); const head = await f.commit('test')
  await assert.rejects(() => f.repo.detail('HEAD; echo secret'), /无效/)
  await assert.rejects(() => f.repo.createBranch(head, '-D', { head, branch: 'main' }), /有效/)
  await assert.rejects(() => f.repo.validateBranch('@{-1}'))
  assert.equal((await f.repo.snapshot()).branches.length, 1)
})

test('in-progress merge and sparse checkout block restoration', async () => {
  const f = await fixture()
  await f.put('file.txt', 'old'); const old = await f.commit('old')
  await f.put('file.txt', 'new'); const head = await f.commit('new')
  await fs.writeFile(path.join(f.root, '.git', 'MERGE_HEAD'), old + '\n')
  await assert.rejects(() => f.repo.restore(old, { head, branch: 'main' }), /合并/)
  await fs.unlink(path.join(f.root, '.git', 'MERGE_HEAD'))
  await f.repo.command(['config', 'core.sparseCheckout', 'true'])
  await assert.rejects(() => f.repo.restore(old, { head, branch: 'main' }), /稀疏/)
  assert.equal(await f.repo.head(), head)
})

test('switch does not overwrite ignored files', async () => {
  const f = await fixture()
  await f.put('cache.txt', 'old tracked'); const old = await f.commit('old')
  await f.repo.command(['branch', 'old', old])
  await fs.unlink(path.join(f.root, 'cache.txt')); await f.put('.gitignore', 'cache.txt\n'); const head = await f.commit('new')
  await f.put('cache.txt', 'precious')
  await assert.rejects(() => f.repo.switchBranch('old', { head, branch: 'main' }))
  assert.equal(await fs.readFile(path.join(f.root, 'cache.txt'), 'utf8'), 'precious')
  assert.equal(await f.repo.head(), head)
})

test('real sparse checkout blocks preview and stale execution while branch-only operations remain usable', async () => {
  const f = await fixture()
  await f.put('visible/a.txt', 'first'); await f.put('hidden/b.txt', 'keep'); const first = await f.commit('first')
  await f.put('visible/a.txt', 'second'); const head = await f.commit('second')
  await f.repo.command(['branch', 'old', first])
  const expected = await f.expected()
  const plan = await f.repo.prepareAction('switchBranch', { name: 'old', expected })
  await f.repo.command(['sparse-checkout', 'set', '--cone', 'visible'])
  assert.equal(await fs.stat(path.join(f.root, 'hidden/b.txt')).catch(() => null), null)
  const index = await fs.readFile(path.join(f.root, '.git/index'))
  await assert.rejects(f.repo.executePrepared(plan), /稀疏/)
  await assert.rejects(f.repo.prepareAction('switchBranch', { name: 'old', expected }), /稀疏/)
  await assert.rejects(f.repo.prepareAction('restore', { oid: first, expected }), /稀疏/)
  assert.equal(await f.repo.head(), head); assert.equal(await f.repo.branch(), 'main')
  assert.deepEqual(await fs.readFile(path.join(f.root, '.git/index')), index)
  assert.equal((await f.repo.operations()).records.length, 0)
  const branch = await f.repo.prepareAction('createBranch', { oid: first, name: 'sparse-safe', expected })
  await f.repo.executePrepared(branch)
  assert.equal(await fs.readFile(path.join(f.root, 'visible/a.txt'), 'utf8'), 'second')
  assert.equal(await fs.stat(path.join(f.root, 'hidden/b.txt')).catch(() => null), null)
})

test('index flags cannot hide worktree changes from switch or restore preflight', async () => {
  const f = await fixture()
  await f.put('a.txt', 'first'); const first = await f.commit('first')
  await f.put('a.txt', 'second'); const head = await f.commit('second')
  await f.repo.command(['branch', 'old', first])
  const expected = await f.expected()
  for (const flag of ['assume-unchanged', 'skip-worktree']) {
    const plan = await f.repo.prepareAction('switchBranch', { name: 'old', expected })
    await f.repo.command(['update-index', `--${flag}`, '--', 'a.txt'])
    await f.put('a.txt', 'hidden change')
    assert.equal(await f.repo.status(), '')
    const index = await fs.readFile(path.join(f.root, '.git/index'))
    await assert.rejects(f.repo.executePrepared(plan), /标记/)
    await assert.rejects(f.repo.prepareAction('restore', { oid: first, expected }), /标记/)
    assert.equal(await f.repo.head(), head); assert.equal(await f.repo.branch(), 'main')
    assert.deepEqual(await fs.readFile(path.join(f.root, '.git/index')), index)
    assert.equal(await fs.readFile(path.join(f.root, 'a.txt'), 'utf8'), 'hidden change')
    await f.put('a.txt', 'second')
    await f.repo.command(['update-index', `--no-${flag}`, '--', 'a.txt'])
  }
  assert.equal((await f.repo.operations()).records.length, 0)
})

test('submodule ignore configuration cannot hide dirty files and restore is rejected before confirmation', async () => {
  const f = await fixture(), sub = await fixture()
  await sub.put('nested.txt', 'original'); await sub.commit('nested')
  await f.put('file.txt', 'first'); const first = await f.commit('first')
  await f.repo.command(['-c', 'protocol.file.allow=always', 'submodule', 'add', sub.root, 'module'])
  const head = await f.commit('with module'), expected = await f.expected()
  await f.repo.command(['branch', 'other', head])
  await assert.rejects(f.repo.prepareAction('restore', { oid: first, expected }), /子模块/)
  const plan = await f.repo.prepareAction('switchBranch', { name: 'other', expected })
  await f.repo.command(['config', 'submodule.module.ignore', 'all'])
  await f.repo.command(['config', 'diff.ignoreSubmodules', 'all'])
  await f.put('module/nested.txt', 'keep my change')
  assert.equal(await f.repo.command(['status', '--porcelain']), '', 'fixture config hides the dirty submodule')
  assert.notEqual(await f.repo.status(), '')
  await assert.rejects(f.repo.executePrepared(plan), /未提交/)
  await assert.rejects(f.repo.prepareAction('switchBranch', { name: 'other', expected }), /未提交/)
  assert.equal(await f.repo.head(), head); assert.equal(await f.repo.branch(), 'main')
  assert.equal(await fs.readFile(path.join(f.root, 'module/nested.txt'), 'utf8'), 'keep my change')
  assert.equal((await f.repo.operations()).records.length, 0)
})

test('linked worktree operation markers block preview and execution using its own Git directory', async () => {
  const f = await fixture()
  await f.put('a.txt', 'first'); const head = await f.commit('first')
  const folder = path.join(testRoot, `linked-${path.basename(f.root)}`)
  await f.repo.command(['worktree', 'add', '-b', 'linked', folder, head])
  const linked = await GitService.open(folder), expected = { head, branch: 'linked' }
  for (const marker of ['MERGE_HEAD', 'CHERRY_PICK_HEAD', 'REVERT_HEAD', 'rebase-merge', 'rebase-apply', 'sequencer']) {
    const plan = await linked.prepareAction('createBranch', { oid: head, name: 'blocked', expected })
    const markerPath = path.resolve(linked.root, (await linked.command(['rev-parse', '--git-path', marker])).trim())
    const directory = ['rebase-merge', 'rebase-apply', 'sequencer'].includes(marker)
    if (directory) await fs.mkdir(markerPath); else await fs.writeFile(markerPath, head + '\n')
    await assert.rejects(linked.executePrepared(plan), /合并、变基/)
    await assert.rejects(linked.prepareAction('createBranch', { oid: head, name: 'blocked', expected }), /合并、变基/)
    if (directory) await fs.rmdir(markerPath); else await fs.unlink(markerPath)
  }
  assert.equal(await linked.head(), head)
  assert.equal((await linked.operations()).records.length, 0)
  await assert.rejects(linked.command(['show-ref', '--verify', 'refs/heads/blocked']))
})

test('history cap always retains an old detached HEAD and respects the limit', async () => {
  const f = await fixture()
  await f.put('file.txt', 'root'); const root = await f.commit('root')
  for (let i = 0; i < 24; i++) { await f.put('file.txt', String(i)); await f.commit(`step ${i}`) }
  await f.repo.command(['switch', '--detach', root])
  const snapshot = await f.repo.snapshot(20)
  assert.equal(snapshot.head, root)
  assert.equal(snapshot.commits.length, 20)
  assert.equal(snapshot.headPinned, true)
  assert.equal(snapshot.truncated, true)
  assert.equal(snapshot.commits.find(commit => commit.oid === root).outsideWindow, true)
})

async function failedRestore() {
  const f = await fixture()
  await f.put('file.txt', 'old\n'); f.old = await f.commit('old')
  await f.put('file.txt', 'new\n'); f.current = await f.commit('new')
  f.hooks = path.join(f.root, '.git', 'hooks-test'); await fs.mkdir(f.hooks)
  f.hook = path.join(f.hooks, 'pre-commit')
  await fs.writeFile(f.hook, '#!/bin/sh\necho recovery-hook-failed >&2\nexit 1\n', { mode: 0o755 })
  await f.repo.command(['config', 'core.hooksPath', f.hooks])
  await assert.rejects(f.repo.restore(f.old, await f.expected()), /recovery-hook-failed/)
  f.record = (await f.repo.operations()).records[0]
  return f
}

test('outcome restore rechecks position after a backup reference hook moves HEAD', async () => {
  const f = await fixture()
  await f.put('a.txt', 'first'); const first = await f.commit('first')
  await f.put('a.txt', 'second'); const head = await f.commit('second'), expected = await f.expected()
  await f.repo.command(['branch', 'other', first])
  await fs.writeFile(path.join(f.root, '.git/hooks/reference-transaction'), '#!/bin/sh\nif test "$1" != committed; then exit 0; fi\nwhile read old new ref; do\ncase "$ref" in refs/heads/gitviz/backup-*) git symbolic-ref HEAD refs/heads/other;; esac\ndone\n', { mode: 0o755 })
  await assert.rejects(f.repo.restore(first, expected), /HEAD 已变化/)
  assert.equal(await f.repo.head(), first); assert.equal(await f.repo.branch(), 'other')
  assert.equal(await fs.readFile(path.join(f.root, 'a.txt'), 'utf8'), 'second')
  const record = (await f.repo.operations()).records[0]
  assert.equal(record.state, 'failed'); assert.equal(record.checkpoint, undefined)
  assert.equal((await f.repo.command(['rev-parse', record.backup])).trim(), head)
})

test('outcome verification detects post-checkout position changes and preserves actual files', async () => {
  const f = await fixture()
  await f.put('a.txt', 'first'); const first = await f.commit('first')
  await f.put('a.txt', 'second'); const head = await f.commit('second')
  await f.repo.command(['branch', 'old', first])
  await fs.writeFile(path.join(f.root, '.git/hooks/post-checkout'), '#!/bin/sh\ngit symbolic-ref HEAD refs/heads/main\n', { mode: 0o755 })
  const plan = await f.repo.prepareAction('switchBranch', { name: 'old', expected: await f.expected() })
  await assert.rejects(f.repo.executePrepared(plan), /结果与确认不一致/)
  assert.equal(await f.repo.head(), head); assert.equal(await f.repo.branch(), 'main')
  assert.equal(await fs.readFile(path.join(f.root, 'a.txt'), 'utf8'), 'first')
  const record = (await f.repo.operations()).records[0]
  assert.equal(record.state, 'failed'); assert.equal(record.result.head, head); assert.equal(record.result.branch, 'main')
})

test('outcome verification rejects a post-commit replacement with the right tree but wrong parent', async () => {
  const f = await fixture()
  await f.put('a.txt', 'first'); const first = await f.commit('first')
  await f.put('a.txt', 'second'); const head = await f.commit('second'), expected = await f.expected()
  const tree = (await f.repo.command(['rev-parse', `${first}^{tree}`])).trim()
  const replacement = (await f.repo.command(['commit-tree', tree, '-p', first, '-m', 'external replacement'])).trim()
  await fs.writeFile(path.join(f.root, '.git/hooks/post-commit'), `#!/bin/sh\ngit rev-parse HEAD > .git/created-by-gitviz\ngit update-ref HEAD ${replacement}\n`, { mode: 0o755 })
  await assert.rejects(f.repo.restore(first, expected), /父提交/)
  const created = (await fs.readFile(path.join(f.root, '.git/created-by-gitviz'), 'utf8')).trim()
  assert.equal((await f.repo.command(['rev-parse', `${created}^`])).trim(), head)
  assert.equal(await f.repo.head(), replacement)
  assert.equal(await fs.readFile(path.join(f.root, 'a.txt'), 'utf8'), 'first')
  const record = (await f.repo.operations()).records[0]
  assert.equal(record.state, 'failed'); assert.equal(record.result.head, replacement)
  assert.equal((await f.repo.command(['rev-parse', record.backup])).trim(), head)
  await assert.rejects(f.repo.pendingCommit(record.id, await f.expected()), /起点不同/)
})

test('outcome verification catches worktree hook edits and preserves the new directory', async () => {
  const f = await fixture()
  await f.put('a.txt', 'original'); const head = await f.commit('first')
  const hooks = path.join(f.root, '.git/hooks')
  await f.repo.command(['config', 'core.hooksPath', hooks])
  await fs.writeFile(path.join(hooks, 'post-checkout'), '#!/bin/sh\nprintf hook-change > a.txt\n', { mode: 0o755 })
  await assert.rejects(f.repo.createWorktree(head, 'trial-hook', testRoot, await f.expected()), /工作区仍有改动/)
  const record = (await f.repo.operations()).records[0]
  assert.equal(record.state, 'failed'); assert.ok(record.worktree)
  assert.equal(await fs.readFile(path.join(record.worktree, 'a.txt'), 'utf8'), 'hook-change')
  assert.equal(await fs.readFile(path.join(f.root, 'a.txt'), 'utf8'), 'original')
  assert.equal(await f.repo.head(), head); assert.equal(await f.repo.branch(), 'main')
  assert.equal((await f.repo.command(['rev-parse', 'refs/heads/trial-hook'])).trim(), head)
})

test('outcome precommit check rejects post-index hook staging during restore without making a commit', async () => {
  const f = await fixture()
  await f.put('a.txt', 'first'); const first = await f.commit('first')
  await f.put('a.txt', 'second'); const head = await f.commit('second'), expected = await f.expected()
  await fs.writeFile(path.join(f.root, '.git/hooks/post-index-change'), '#!/bin/sh\nif test -f .git/race-fired; then exit 0; fi\nprintf fired > .git/race-fired\nprintf external-staging > external.txt\ngit add -- external.txt\n', { mode: 0o755 })
  await assert.rejects(f.repo.restore(first, expected), /恢复暂存内容不同/)
  assert.equal(await f.repo.head(), head)
  assert.equal(await fs.readFile(path.join(f.root, 'external.txt'), 'utf8'), 'external-staging')
  assert.match(await f.repo.command(['diff', '--cached', '--name-only']), /external.txt/)
  const record = (await f.repo.operations()).records[0]
  assert.equal(record.state, 'failed'); assert.ok(record.backup)
  assert.equal(record.checkpoint, undefined)
  await assert.rejects(f.repo.pendingCommit(record.id, expected), /没有可继续/)
})

test('persistent recovery preview is read-only and continuing keeps identity, parent, backup and exact tree', async () => {
  const f = await failedRestore(), record = f.record, expected = await f.expected()
  assert.equal(record.state, 'failed'); assert.equal(record.action, 'restore'); assert.equal(record.before.head, f.current)
  assert.equal(record.params.oid, f.old); assert.match(record.error, /recovery-hook-failed/)
  const reopened = await GitService.open(f.root)
  const index = await fs.readFile(path.join(f.root, '.git', 'index'))
  assert.equal((await reopened.pendingCommit(record.id, expected)).checkpoint.tree, record.checkpoint.tree)
  assert.deepEqual(await fs.readFile(path.join(f.root, '.git', 'index')), index)
  assert.equal((await reopened.operations()).records[0].attempts, 1)
  await assert.rejects(reopened.resumeCommit(record.id, expected, record.checkpoint), /recovery-hook-failed/)
  assert.equal((await reopened.operations()).records[0].attempts, 2)
  await fs.unlink(f.hook)
  const result = await reopened.resumeCommit(record.id, expected, record.checkpoint)
  assert.equal((await reopened.command(['rev-parse', 'HEAD^'])).trim(), f.current)
  assert.equal((await reopened.command(['rev-parse', 'HEAD^{tree}'])).trim(), record.checkpoint.tree)
  assert.equal((await reopened.command(['rev-parse', record.backup])).trim(), f.current)
  assert.match(await reopened.command(['log', '-1', '--format=%an <%ae>']), /Gitviz Test Fixture <fixture@example.invalid>/)
  assert.equal(await reopened.status(), '')
  assert.equal(result.operationId, record.id)
  const saved = (await reopened.operations()).records[0]
  assert.equal(saved.state, 'completed'); assert.equal(saved.attempts, 3); assert.match(saved.lastError, /recovery-hook-failed/)
  await assert.rejects(reopened.resumeCommit(record.id, await f.expected()), /没有可继续/)
})

test('recovery rejects changed worktree, index, untracked files, HEAD and checkpoint after preview', async () => {
  const f = await failedRestore(), expected = await f.expected(), id = f.record.id
  await fs.unlink(f.hook)
  await f.put('file.txt', 'later edit\n')
  await assert.rejects(f.repo.pendingCommit(id, expected), /工作文件/)
  await f.repo.command(['add', '--', 'file.txt'])
  await assert.rejects(f.repo.resumeCommit(id, expected), /暂存区/)
  await f.repo.command(['restore', `--source=${f.old}`, '--staged', '--worktree', '--', '.'])
  await f.put('untracked.txt', 'keep me')
  await assert.rejects(f.repo.pendingCommit(id, expected), /未跟踪/)
  await fs.unlink(path.join(f.root, 'untracked.txt'))
  await f.repo.command(['update-ref', 'refs/heads/main', f.old])
  await assert.rejects(f.repo.resumeCommit(id, expected), /HEAD 已变化/)
  await f.repo.command(['update-ref', 'refs/heads/main', f.current])
  await assert.rejects(f.repo.resumeCommit(id, expected, { ...f.record.checkpoint, message: 'different confirmed message' }), /检查点已变化/)
  assert.equal(await f.repo.head(), f.current)
  assert.equal(await fs.readFile(path.join(f.root, 'file.txt'), 'utf8'), 'old\n')
})

test('journal pages, linked worktree isolation, corrupt records and metadata junction protection', async () => {
  const f = await fixture(); await f.put('file.txt', 'saved'); const head = await f.commit('saved')
  await f.repo.createBranch(head, 'one', await f.expected())
  await f.repo.createBranch(head, 'two', await f.expected())
  const first = await f.repo.operations({ limit: 1 }), next = await f.repo.operations({ before: first.nextCursor, limit: 1 })
  assert.equal(first.records.length, 1); assert.equal(next.records.length, 1); assert.notEqual(first.records[0].id, next.records[0].id)
  const created = await f.repo.createWorktree(head, 'linked', path.join(testRoot, 'worktrees'), await f.expected())
  const linked = await GitService.open(created.worktree)
  assert.deepEqual((await linked.operations()).records, [])
  await linked.createBranch(head, 'linked-new', { head, branch: 'linked' })
  assert.equal((await linked.operations()).records.length, 1); assert.equal((await f.repo.operations()).records.length, 3)
  const directory = await f.repo.journal.directory()
  const file = path.join(directory, first.records[0].id + '.json')
  await fs.writeFile(file, '{broken')
  assert.equal((await f.repo.operations()).records.find(record => record.id === first.records[0].id).state, 'unreadable')
  await assert.rejects(f.repo.journal.read('../config'), /无效/)
  const fake = path.join(f.root, '.git', 'metadata-target'); await fs.mkdir(fake)
  await fs.rename(directory, directory + '-original')
  await fs.symlink(fake, directory, process.platform === 'win32' ? 'junction' : 'dir')
  await assert.rejects(f.repo.operations(), /链接/)
  await assert.rejects(f.repo.createBranch(head, 'blocked', await f.expected()), /链接/)
  await assert.rejects(f.repo.command(['show-ref', '--verify', 'refs/heads/blocked']))
})
