const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const path = require('node:path')
const os = require('node:os')
const { GitService } = require('../extensions/vscode/git-service.cjs')
const testRoot = process.env.GITVIZ_TEST_ROOT || (process.platform === 'win32' ? 'F:/Codex/work/gitviz-tests' : path.join(os.tmpdir(), 'gitviz-tests'))

async function fixture() {
  await fs.mkdir(testRoot, { recursive: true })
  const root = await fs.mkdtemp(path.join(testRoot, 'repo-'))
  const repo = new GitService(root)
  await repo.command(['init', '-b', 'main'])
  await repo.command(['config', 'user.name', 'Gitviz Test Fixture'])
  await repo.command(['config', 'user.email', 'fixture@example.invalid'])
  await repo.command(['config', 'commit.gpgsign', 'false'])
  await repo.command(['config', 'core.autocrlf', 'false'])
  const put = async (name, content) => { await fs.mkdir(path.dirname(path.join(root, name)), { recursive: true }); await fs.writeFile(path.join(root, name), content) }
  const commit = async message => { await repo.command(['add', '--all']); await repo.command(['commit', '-m', message]); return repo.head() }
  const expected = async () => ({ head: await repo.head(), branch: await repo.branch() })
  return { root, repo, put, commit, expected }
}

test('empty repository, root commit, unicode and special filenames', async () => {
  const f = await fixture()
  assert.deepEqual((await f.repo.snapshot()).commits, [])
  const name = '中文 space $name [1].txt'
  await f.put(name, '最初内容\n')
  const first = await f.commit('起点 · 中文')
  const data = await f.repo.snapshot()
  assert.equal(data.commits[0].message, '起点 · 中文')
  assert.equal(data.branch, 'main'); assert.equal(data.head, first)
  const detail = await f.repo.detail(first)
  assert.equal(detail.from, null); assert.equal(detail.files[0].status, 'A')
  assert.equal(await f.repo.readFile(first, name), '最初内容\n')
  assert.equal(await f.repo.readFile(first, 'absent.txt'), '')
  assert.equal(await f.repo.readFile(null, name), '')
})

test('real merge includes both parents, annotated tag, detached HEAD', async () => {
  const f = await fixture()
  await f.put('base.txt', 'base'); const root = await f.commit('base')
  await f.repo.command(['switch', '-c', 'feature'])
  await f.put('feature.txt', 'feature'); const feature = await f.commit('feature')
  await f.repo.command(['switch', 'main'])
  await f.put('main.txt', 'main'); const main = await f.commit('main')
  await f.repo.command(['merge', '--no-ff', 'feature', '-m', 'merge'])
  const head = await f.repo.head()
  await f.repo.command(['tag', '-a', 'v1', '-m', 'release'])
  const data = await f.repo.snapshot()
  assert.deepEqual(data.commits[0].parents, [main, feature])
  assert.equal(data.tags[0].oid, head); assert.equal(data.commits.length, 4)
  await f.repo.command(['switch', '--detach', root])
  assert.equal((await f.repo.snapshot()).branch, '')
  await assert.rejects(() => f.repo.restore(feature, { head: root, branch: '' }), /游离/)
})

test('rename and deleted/added contents are directional', async () => {
  const f = await fixture()
  await f.put('old name.txt', 'same\n'); await f.put('removed.txt', 'bye'); const before = await f.commit('before')
  await fs.rename(path.join(f.root, 'old name.txt'), path.join(f.root, 'new name.txt'))
  await fs.unlink(path.join(f.root, 'removed.txt')); await f.put('added.txt', 'new')
  const after = await f.commit('after')
  const files = await f.repo.files(before, after)
  assert.equal(files.find(file => file.path === 'new name.txt').oldPath, 'old name.txt')
  assert.equal(files.find(file => file.path === 'removed.txt').status, 'D')
  assert.equal(files.find(file => file.path === 'added.txt').status, 'A')
  assert.equal(await f.repo.readFile(before, 'old name.txt'), 'same\n')
  assert.equal(await f.repo.readFile(after, 'new name.txt'), 'same\n')
})

test('branch creation is non-switching and checkout synchronizes real worktree', async () => {
  const f = await fixture()
  await f.put('file.txt', 'old'); const old = await f.commit('old')
  await f.put('file.txt', 'new'); const current = await f.commit('new')
  await f.repo.createBranch(old, 'if-old', await f.expected())
  assert.equal(await f.repo.head(), current)
  await f.repo.switchBranch('if-old', await f.expected())
  assert.equal(await fs.readFile(path.join(f.root, 'file.txt'), 'utf8'), 'old')
  assert.equal(await f.repo.branch(), 'if-old')
})

test('isolated worktree leaves original dirty files and HEAD untouched', async () => {
  const f = await fixture()
  await f.put('file.txt', 'saved'); const head = await f.commit('saved')
  await f.put('file.txt', 'unsaved')
  const result = await f.repo.createWorktree(head, 'if-test', path.join(testRoot, 'worktrees'), await f.expected())
  assert.equal(await fs.readFile(path.join(result.worktree, 'file.txt'), 'utf8'), 'saved')
  assert.equal(await fs.readFile(path.join(f.root, 'file.txt'), 'utf8'), 'unsaved')
  assert.equal(await f.repo.head(), head)
  assert.equal(await f.repo.branch(), 'main')
})

test('restore creates new commit with target tree, retains history and backup', async () => {
  const f = await fixture()
  await f.put('file.txt', 'old'); await f.put('removed.txt', 'restore me'); const old = await f.commit('old')
  await f.put('file.txt', 'new'); await fs.unlink(path.join(f.root, 'removed.txt')); await f.put('added.txt', 'remove me'); const before = await f.commit('new')
  const result = await f.repo.restore(old, await f.expected())
  assert.notEqual(result.head, old); assert.notEqual(result.head, before)
  assert.equal((await f.repo.command(['rev-parse', `${result.head}^`])).trim(), before)
  assert.equal((await f.repo.command(['rev-parse', `${old}^{tree}`])).trim(), (await f.repo.command(['rev-parse', 'HEAD^{tree}'])).trim())
  assert.equal((await f.repo.command(['rev-parse', result.backup])).trim(), before)
  assert.equal(await f.repo.status(), '')
  assert.equal(await fs.readFile(path.join(f.root, 'file.txt'), 'utf8'), 'old')
  assert.equal(await fs.readFile(path.join(f.root, 'removed.txt'), 'utf8'), 'restore me')
  assert.equal(await fs.stat(path.join(f.root, 'added.txt')).catch(() => null), null)
  await f.repo.command(['fsck', '--no-dangling'])
})

test('dirty/untracked files, stale HEAD and busy operations reject mutations', async () => {
  const f = await fixture()
  await f.put('file.txt', 'old'); const old = await f.commit('old'); const expected = await f.expected()
  await f.put('new.txt', 'untracked')
  await assert.rejects(() => f.repo.restore(old, expected), /未提交/)
  await assert.rejects(() => f.repo.switchBranch('main', expected), /未提交/)
  await f.commit('new')
  await assert.rejects(() => f.repo.restore(old, expected), /已变化/)
  f.repo.busy = true
  await assert.rejects(() => f.repo.createBranch(old, 'nope', expected), /正在进行/)
})

test('ignored files that would be overwritten are protected', async () => {
  const f = await fixture()
  await f.put('cache.txt', 'tracked old'); const old = await f.commit('old')
  await fs.unlink(path.join(f.root, 'cache.txt')); await f.put('.gitignore', 'cache.txt\n'); const current = await f.commit('ignore')
  await f.put('cache.txt', 'precious ignored')
  await assert.rejects(() => f.repo.restore(old, { head: current, branch: 'main' }), /被忽略/)
  assert.equal(await fs.readFile(path.join(f.root, 'cache.txt'), 'utf8'), 'precious ignored')
  assert.equal(await f.repo.head(), current)
})

test('commit hook failure retains backup, target staged content and old HEAD', async () => {
  const f = await fixture()
  await f.put('file.txt', 'old'); const old = await f.commit('old')
  await f.put('file.txt', 'new'); const current = await f.commit('new')
  const hooks = path.join(f.root, '.git', 'hooks-test')
  await fs.mkdir(hooks)
  await fs.writeFile(path.join(hooks, 'pre-commit'), '#!/bin/sh\necho test-hook-rejected >&2\nexit 1\n', { mode: 0o755 })
  await f.repo.command(['config', 'core.hooksPath', hooks])
  await assert.rejects(() => f.repo.restore(old, { head: current, branch: 'main' }), /恢复未完成.*test-hook-rejected/s)
  assert.equal(await f.repo.head(), current)
  assert.equal(await fs.readFile(path.join(f.root, 'file.txt'), 'utf8'), 'old')
  assert.ok(await f.repo.status())
  assert.ok((await f.repo.snapshot()).branches.some(ref => ref.name.startsWith('gitviz/backup-') && ref.oid === current))
})

test('invalid OIDs and branch expressions never become shell commands', async () => {
  const f = await fixture()
  await f.put('file.txt', 'test'); const head = await f.commit('test')
  await assert.rejects(() => f.repo.detail('HEAD; echo secret'), /无效/)
  await assert.rejects(() => f.repo.createBranch(head, '-D', { head, branch: 'main' }), /有效/)
  await assert.rejects(() => f.repo.validateBranch('@{-1}'))
  assert.equal((await f.repo.snapshot()).branches.length, 1)
})

test('in-progress merge and sparse checkout block restoration', async () => {
  const f = await fixture()
  await f.put('file.txt', 'old'); const old = await f.commit('old')
  await f.put('file.txt', 'new'); const head = await f.commit('new')
  await fs.writeFile(path.join(f.root, '.git', 'MERGE_HEAD'), old + '\n')
  await assert.rejects(() => f.repo.restore(old, { head, branch: 'main' }), /合并/)
  await fs.unlink(path.join(f.root, '.git', 'MERGE_HEAD'))
  await f.repo.command(['config', 'core.sparseCheckout', 'true'])
  await assert.rejects(() => f.repo.restore(old, { head, branch: 'main' }), /稀疏/)
  assert.equal(await f.repo.head(), head)
})

test('switch does not overwrite ignored files', async () => {
  const f = await fixture()
  await f.put('cache.txt', 'old tracked'); const old = await f.commit('old')
  await f.repo.command(['branch', 'old', old])
  await fs.unlink(path.join(f.root, 'cache.txt')); await f.put('.gitignore', 'cache.txt\n'); const head = await f.commit('new')
  await f.put('cache.txt', 'precious')
  await assert.rejects(() => f.repo.switchBranch('old', { head, branch: 'main' }))
  assert.equal(await fs.readFile(path.join(f.root, 'cache.txt'), 'utf8'), 'precious')
  assert.equal(await f.repo.head(), head)
})

test('history cap always retains an old detached HEAD and respects the limit', async () => {
  const f = await fixture()
  await f.put('file.txt', 'root'); const root = await f.commit('root')
  for (let i = 0; i < 24; i++) { await f.put('file.txt', String(i)); await f.commit(`step ${i}`) }
  await f.repo.command(['switch', '--detach', root])
  const snapshot = await f.repo.snapshot(20)
  assert.equal(snapshot.head, root)
  assert.equal(snapshot.commits.length, 20)
  assert.equal(snapshot.headPinned, true)
  assert.equal(snapshot.truncated, true)
  assert.equal(snapshot.commits.find(commit => commit.oid === root).outsideWindow, true)
})
